### ISSUE TITLE
authentication failure

### ISSUE THREAD

**Issue by aandrejj** [start-jsk/telemba#11]
Hello,
I'm trying to create Telemba.
-HW works fine ,  
-firmware  v 0.1.3 is uploaded to Pic,  
-TelembaController (Android application) is installed from Google-Playstore. Looks fine, but...
...But I cannot SingIn from my TelembaController. 
I'm getting message 'authentication failure' when I'm trying to put username  'guest' and same password.
What's  wrong?  Thank you for help.  :-)

**Comment by longjie** [comment]
HI,

This project is no longer maintained. The authentication is for MQTT server hosted at "telemba.jp" but no longer alive. In addition, google hangouts abandoned their apps framework, so you have to find another way for remote MQTT client.

**Comment by aandrejj** [comment]
It's a pity, 
But thank you for answer.  :-)
